// Configuration for Pocket backend
// This file is auto-generated by build-for-service.js

// Active configuration for Pocket
const ACTIVE_CONFIG = {
  "SERVICE_NAME": "Pocket",
  "BASE_DOMAIN": "getpocket.com",
  "API_VERSION": "v3",
  "BRANDING": {
    "name": "Save to Pocket",
    "shortName": "Pocket",
    "description": "The easiest, fastest way to capture articles, videos, and more."
  }
}

// Generate URLs based on active configuration
export const CONFIG = {
  ...ACTIVE_CONFIG,
  URLS: {
    AUTH: `https://${ACTIVE_CONFIG.BASE_DOMAIN}/signup?src=extension&route=/extension_login_success`,
    LOGOUT: `https://${ACTIVE_CONFIG.BASE_DOMAIN}/lo`,
    API_BASE: `https://${ACTIVE_CONFIG.BASE_DOMAIN}/${ACTIVE_CONFIG.API_VERSION}/`,
    USER_LIST: `https://${ACTIVE_CONFIG.BASE_DOMAIN}/saves`,
    USER_HOME: `https://${ACTIVE_CONFIG.BASE_DOMAIN}/home`,
    HELP: `https://help.${ACTIVE_CONFIG.BASE_DOMAIN}/`,
    CONTACT: `https://${ACTIVE_CONFIG.BASE_DOMAIN}/contact_support?field3=Question%20about%20${ACTIVE_CONFIG.SERVICE_NAME}%20Extension`,
    PRIVACY: `https://${ACTIVE_CONFIG.BASE_DOMAIN}/privacy/?src=extension`,
    TERMS: `https://${ACTIVE_CONFIG.BASE_DOMAIN}/tos/?src=extension`,
  }
}

// Consumer key for Pocket
export const CONSUMER_KEY = '__consumerKey__'

// Extension-specific constants that don't change
export const EXTENSION_CONSTANTS = {
  SET_SHORTCUTS: 'chrome://extensions/configureCommands',
  LOGIN_SUCCESS_PATH: '/extension_login_success*',
  LOGOUT_ERROR_PATH: '/login?e=4'
}
